name: HW2

on:
  push:
    branches: [ "main" ]
    paths:
      - hw2/**

jobs:
  HW2_job:
    name: HW2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd hw2
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install --upgrade autopep8
        pip install pylint
        pip install bandit
    - name: Test with pytest
      run: |
        pytest ./hw2
    - name: Run tests
      run: |
        cd hw2
        pytest --cov
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
    - name: AutoPep8
      run: |
        autopep8 --in-place --aggressive --recursive ./hw2
    - name: pylint
      run: |
        pylint ./hw2 > pylint-actions.txt
    - name: Bandit
      run: |
        bandit -r -ll ./hw2 > bandit-actions.txt
