name: Pylint

on:
  push:
    branches: [ "main" ]
    paths:
      - hw2/**

jobs:
  HW2_job:
    name: HW2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd hw2
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install pylint
    - name: pylint
      run: |
        pylint ./hw2 > pylint_report.txt || true
    - name: Upload PyLint report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint_report.txt

