name: Python application

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - hw1/**

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install autopep8
        pip install pylint
        pip install bandit
    - name: Test with pytest
      run: |
        pytest
    - name: Run tests
      run: |
        pytest --cov
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
    - name: autopep8
      run: |
        autopep8
    - name: pylint
      run: |
        pylint
    - name: Bandit
      run: |
        autopep8
      # with:
      #     args: --recursive --in-place --aggressive --aggressive .
            
